export default {
	"MAYAN_FORWARDER_CONTRACT": "0x0654874eb7F59C6f5b39931FC45dC45337c967c3",
	"MAYAN_PROGRAM_ID": "FC4eXxkyrMPTjiYUpp4EAnkmwMbQyZ6NDCh1kfLn6vsf",
	"AUCTION_PROGRAM_ID": "8QJmxZcEzwuYmCPy6XqgN2sHcYCcFq6AEfBMJZZuLo5a",
	"MCTP_PROGRAM_ID": "Awm2zSgzMGTRraAVjRvshqLehy7mJ2Qr3maURDsoDmwi",
	"SWIFT_PROGRAM_ID": "5vBpQGxxnzjhv3FNFVpVmGWsUhhNFu4xTbyGs3W2Sbbx",
	"WORMHOLE_PROGRAM_ID": "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth",
	"CCTP_CORE_PROGRAM_ID": "CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd",
	"CCTP_TOKEN_PROGRAM_ID": "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3",
	"TOKEN_PROGRAM_ID": "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
	"ASSOCIATED_TOKEN_PROGRAM_ID": "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL",
	"LOOKUP_TABLE": "AAJD5ef3combuWT586MxuWPwff3VtWu3FXVUPBJesoiy",
	"EXPLORER_URL": "https://explorer-api.mayan.finance/v3",
	"PRICE_URL": "https://price-api.mayan.finance/v3",
	"RELAYER_URL": "https://relayer-api.mayan.finance/v3",
}
